### ISSUE TITLE
document how hoplon/javelin addresses performance in the wiki

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#100]
Commonly seen in chat are questions/confusion as to how Hoplon might perform.

When I first started working with Hoplon, I assumed it was rebuilding a lot of the DOM quite frequently and was worried about how that might affect performance negatively.

Since then I've learned a few things that make me feel more comfortable:
- formula cells only recalculate when the cells they depend on change, so a lot of things will only recalculate infrequently (only when their dependencies change and this change propagates).
- the DOM is actually largely static, `do!` handles most of the dynamism by adding watches whenever it is passed a cell. This means we can do things like caching the DOM (if we wanted to remove it and put it back).
- there's work towards making non-static DOM behaviour a lot easier to handle in terms of memory management and caching, etc. at #93 
- it's actually very easy to show/hide elements with `:toggle` in `do!`, and this solves many use-cases for wanting to add/remove elements to the DOM
- calculating things "in JS" is faster than manipulating the DOM, so if you were writing code where you read-DOM->calculate->write-DOM repeatedly to the DOM previously, this is comparing apples to oranges when considering read-memory->calculate->write-changes-only-to-DOM style code.

**Comment by levitanong** [comment]
@thedavidmeister What do you think about putting all these in a FAQ first? I'm not sure yet how to approach the introduction thing you mentioned, and how it should fit into the rest of our documentation. (like Readme and Get Started) Also, I'm wondering if we should consider using another thing for documentation, as the number of articles on our sidebar is quickly ballooning :P

**Comment by levitanong** [comment]
Scratch the last bit about the sidebar ballooning. Discovered the SIDEBAR. SO AMAZING. Now our docs can be organized!!!

**Comment by thedavidmeister** [comment]
@levitanong nice work on the sidebar, yay! tbh, while we're just throwing up issues for docs and working through it, I think organisation will probably get worse before it gets better

**Comment by flyboarder** [comment]
@thedavidmeister I reworded your original post and included it here: https://github.com/hoplon/hoplon/wiki/Performance

**Comment by thedavidmeister** [comment]
@flyboarder yes i like it and i added to it as well based on recent slack discussions
