### ISSUE TITLE
merge-kids fails with NPE due to removeChild on a non-existing element

### ISSUE THREAD

**Issue by dm3** [hoplon/hoplon#106]
See https://github.com/dm3/hoplon-bugs/tree/master/remove-child-bug for the reproducible project. Seems like a bug in `merge-kids`.

**Comment by micha** [comment]
This has something to do with the crazy stuff the jquery plugin creates in the DOM. A workaround is:
```clojure
(with-page-load (.reload js/location))
```
in your _index.cljs.hl_ file.

**Comment by dm3** [comment]
Hmm, looking at it I can't find anything extremely crazy. It seems like for proper reload the autocomplete could be destroyed through its `destroy` method. Is there a way to hook that up into the reload process without having to reload the page?

**Comment by micha** [comment]
Yes, you can evaluate arbitrary code in the body of `with-page-load`.

**Comment by dm3** [comment]
I investigated some more - the problem causing the exception is jQuery UI Widget registering an `onremove` callback. In case of Autocomplete, it cleans up after itself by removing the additional menu and "live region" elements from the parent (body). The following happens:

1. `merge-kids` removes old Autocomplete `input`
2. `onremove` triggered - menu `ul` is removed from `body`
3. `merge-kids` tries to remove the menu `ul` and fails

I think this is a generic problem that we could run into with arbitrary javascript code and some sort of a solution in Hoplon would be nice to have. I can think of two for now: 

1. wrapping `removeChild` in `try-catch` - might hide possible issues with the logic
2. checking whether the node to be removed has `this` as its parent in `merge-kids` - might have performance issues, although we can write some benchmarks and test it
