### ISSUE TITLE
head and body elements error when passed a cell

### ISSUE THREAD

**Issue by jumblerg** [hoplon/hoplon#116]
when a singleton constructor is passed cell, it will be added to the hoplon kids atom, triggering a call to merge-kids with the cell itself instead of the expected element it contains.  the cell needs to be watched instead so its contents will be swapped into `-hoplonKids` when it changes. 

`appendChild`, called by `addChildren!`, already contains the functionality to do this.

**Comment by dm3** [comment]
related to #98?

**Comment by jumblerg** [comment]
yep, same issue.  closing as a duplicate.
