### ISSUE TITLE
consider eliminating the dispatch of do!, on! multimethods on attributes of header elements.

### ISSUE THREAD

**Issue by jumblerg** [hoplon/hoplon#119]
a minor optimization.

**Comment by thedavidmeister** [comment]
would this cause problems for `:load` events on script tags?

**Comment by flyboarder** [comment]
I think we should close this for now, dispatching for on and do with header elements can be useful in cases where you want to toggle css files, for example, also attributes which are not passed a cell do not have watchers attached. Otherwise feel free to reopen.
