### ISSUE TITLE
loop-tpl bindings should be lenses instead of simple formula cells

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#121]
Will allow the following:

```clj
(let [items (cell [1 2 3])]
  (div
    (loop-tpl :bindings [item items]
      (div
        (text "item: ~{item}")
        (button :click #(swap! item * 2
          "x2")))))
```

What do you guys think?

**Comment by alandipert** [comment]
Interesting! In the example, items is an input cell and I can see how this makes sense.  It doesn't seem to make sense if items were a formula cell. Perhaps item should be a lens if and only if the right side of the binding is a lens or an input cell?

**Comment by levitanong** [comment]
@alandipert yeah, definitely!

**Comment by levitanong** [comment]
@alandipert So I'm trying my hand at implementing this, but I'm running into a roadblock.
So I've modified `loop-tpl*` like so:

```clj
(defn loop-tpl*
  [items tpl]
  (let [on-deck   (atom ())
        items-seq (cell= (seq items))
        ;; the relevant bit: ith-item now returns a lens.
        ith-item  (fn [i]
                    (if (or (input? items) (lens? items))
                      (cell= (safe-nth items-seq i)
                             #(swap! items assoc i %))
                      (cell= (safe-nth items-seq i))))
        shift!    #(with-let [x (first @%)] (swap! % rest))]
    (with-let [current (cell [])]
      (do-watch items-seq
                (fn [old-items new-items]
                  (let [old  (count old-items)
                        new  (count new-items)
                        diff (- new old)]
                    (cond (pos? diff)
                          (doseq [i (range old new)]
                            (let [e (or (shift! on-deck) (tpl (ith-item i)))]
                              (swap! current conj e)))
                          (neg? diff)
                          (dotimes [_ (- diff)]
                            (let [e (peek @current)]
                              (swap! current pop)
```

The road block is in the macro side. Inside `loop-tpl` there is a `j/cell-let`, and this is where things break down. `j/cell-let` internally uses a `cell-map`, which appears to return a sequence of formula cells. I know this is necessary for all the destructuring stuff, but at this point I'm stumped. Any advice on how to proceed?

**Comment by laforge49** [comment]
Can the formula cells also be lenses?

**Comment by micha** [comment]
@levitanong you can create your own lens in the `loop-tpl` body:

```clojure
(let [items (cell [1 2 3])]
  (div
    (loop-tpl :bindings [[i item] (cell= (map-indexed list items))]
      (let [item (cell= item #(swap! items assoc @i %))]
        (div
          (text "item: ~{item}")
          (button :click #(swap! item * 2) "x2"))))))
```

It seems like we can't make a general solution there, so perhaps a macro
that expands to `loop-tpl` with the lens binding is what we want?

**Comment by micha** [comment]
@laforge49 lenses do act like formula cells with respect to the values they contain, but they support some notion of `swap!` and `reset!`, which formulas do not.

**Comment by levitanong** [comment]
@micha Yeah, that's what I've been doing. I found myself thinking it would be cleaner and awesome if the loop-tpl bindings bound lens. It would also be an easier api for newcomers (maybe).

I'm not sure how a macro can expand to a `loop-tpl` with a lens binding, because internally, `loop-tpl` binds to formula cells to support destructuring. But then again, I'm still new to clojure, so I don't know what other witchcraft you can do with macros. :P

Then again, maybe the conditionality of the lens behavior is undesirable. Perhaps it would add too much Black Box Magic™. I am loathe to see hoplon turn into angular. :stuck_out_tongue_winking_eye: 

@laforge49 afaik, lenses are just formula cells with setters. (they're the second argument to `cell=`)

**Comment by micha** [comment]
Yes, the `cell-let` part is tricky because it doesn't really know about destructuring or what the bindings mean&mdash;it passes that through to the Clojure destructuring macros. Maybe `clojure.core/destructure` is useful here?

**Comment by levitanong** [comment]
@micha `destructure` is good for defining getters for formula cells, but to my knowledge, deriving setters from whatever `destructure` spits out is prohibitively difficult. So if ever, this `for-lens` should be something entirely separate, without any destructuring. At this point, I'm not sure this should even exist. :P

**Comment by levitanong** [comment]
Closing, because prolly a bad idea.
