### ISSUE TITLE
if-tpl and handlers inside the children nodes

### ISSUE THREAD

**Issue by roti** [hoplon/hoplon#126]
Hi,

I'm not sure if this is a bug, but I'm posting it anyway. `if-tpl` does not seem to work when the predicate cell is changed by a handler from one of its nodes. Example:
```clojure
(defc visible false)
;;....
(button "show!" :click #(swap! visible not))
(div
  (if-tpl visible
          (button "hide!" :click #(swap! visible not))))
```
Clicking only on "show!" works as expected: second button is shown and hidden alternatively.

Clicking on "show!" and then on "hide!" works only the first time:
* click on "show!" -> second button becomes visible
* click on "hide!" -> second button disappears
* click on "show!" again -> second button becomes visible, as expected
* click on "hide!" again -> nothing happens

Cheers,
Răzvan

**Comment by dm3** [comment]
Works for me on a super simple project with just your code snippet. Did you try on the latest master?

**Comment by roti** [comment]
No, I tried with `if-tpl` copied over to my namespace. Is the master available on clojars? Can I use it without copying it to my project?

**Comment by roti** [comment]
I just tested it with the new 6.0.0-alpha14 release and it works fine. Great.
