### ISSUE TITLE
Design.md should prolly be in wiki

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#128]
https://github.com/hoplon/hoplon/blob/master/Design.md

**Comment by mynomoto** [comment]
I'm not sure if this is a good idea as that document is not up to date and there are differences between the current implementation and what is described there.

**Comment by flyboarder** [comment]
Moved to https://github.com/hoplon/hoplon/wiki/HLisp which has been a stub for a while. Removing the Design.md in `7.2` branch.
