### ISSUE TITLE
Setting the option element's value to nil uses its text value

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#131]
```clj
(select :change #(reset! selected-item %@)
  (option :value nil "Nothing Selected") 
  ;; When this is selected, `select` will have 
  ;; a value of "Nothing Selected" instead of nil.
  (for-tpl [item items]
    (option :value item (pretty-string item))))
```

This issue prevents the above from properly executing the change function.

**Comment by rwillig** [comment]
I may be wrong about this, but my understanding is that all HTML input values are supposed to be strings. I don't think this is a hoplon issue, but more about the way html form elements handle values. In my programs, i usually will do (option :value "" "Nothing Selected") and get the behavior i'm expecting.

**Comment by levitanong** [comment]
This works! Thanks, @rwillig!
