### ISSUE TITLE
cell-let converts input cells to formula cells

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#132]
```clj
(cell-let [a (cell nil)]
  (swap! a 2))
```

Will complain I can't `swap!` or `reset!` a formula cell.

**Comment by onetom** [comment]
`cell-let` is [javelin macro](https://github.com/hoplon/javelin/blob/7491812b56a11847c763fc1b5df9926d9b6d414c/src/javelin/core.clj#L219-L223) so it's not a hoplon issue.

According to its documentation in the Javelin readme, what you described is the expected behaviour:
```
(cell-let [binding-form c] body*)
;; Given a cell c and a binding form, binds names in the binding form to formula
;; cells containing the destructured values (these values will update as the
;; value of c changes) and evaluates the body expressions.
```
