### ISSUE TITLE
Make a guide for webdriver testing

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#134]
@thedavidmeister :D

**Comment by onetom** [comment]
Here is an up to date starting point: https://github.com/greywolve/clj-webdriver-boilerplate
Then I was just trying today https://github.com/AvisoNovate/taxi-toolkit which is supposed to be an even higher level convenience layer on top of https://github.com/semperos/clj-webdriver/wiki/Introduction%3A-Taxi

**Comment by thedavidmeister** [comment]
i no longer think this is the best way of testing hoplon components - use unit tests instead :)

core already has examples on how to do this in its own test suite
