### ISSUE TITLE
Hoplon 6 alpha 10+ is not compatible with jquery-ui autocomplete using jquery 2.x

### ISSUE THREAD

**Issue by mynomoto** [hoplon/hoplon#135]
Until Hoplon 6 alpha 1 I could use jquery 2.x and have jquery-ui autocomplete working but it stopped working correctly on alpha 10 and the problem persists at least until alpha 15. I'm not sure if Hoplon should support jquery 2.x, but if it should, then this is a regression.

**Comment by mynomoto** [comment]
Repro case: https://github.com/mynomoto/minimal-jquery-autocomplete-bug
Master branch uses alpha 14 (but I tried alpha 15 also) and when you start to type "a" slowly it start to append duplicates on the autocomplete list. The branch "hoplon-alpha1" works fine, only changes being the hoplon version.

**Comment by dm3** [comment]
@mynomoto: I use jQuery Autocomplete with jQuery 1.11 and it works fine. 

Could you please take a look at https://github.com/dm3/hoplon-bugs/tree/master/remove-child-bug? The issue in my repo was resolved by not doing `jQuery.remove(el)` in `merge-kids` as it was arbitrarily mutating DOM elements. Maybe that's the point when your autocomplete broke. If so we'd need to think of yet another, probably Autocomplete-specific, solution.

Could you try your implementation with jQuery 1.11?

**Comment by mynomoto** [comment]
@dm3: oh yeah, jquery 1.x works just fine and I'm currently using 1.12.2-0 from cljsjs. This is not blocking in any way for me, after I found that jquery 2.x with hoplon 6 alpha 10+ was the cause.

It's just that if jquery 2 should be supported, then this is a problem. Otherwise this issue should be closed and we should better document that jquery 2.x is not supported.

About your branch you mean using jquery 2.x? Because you have jquery 1.11.3-0 there.

**Comment by flyboarder** [comment]
@mynomoto I am going to close this as it's related to very old versions of Hoplon, I tried on your example repo after updating the dependencies and got errors related to jQuery, however the autocomplete ui was working.
