### ISSUE TITLE
Window load event

### ISSUE THREAD

**Issue by flyboarder** [hoplon/hoplon#137]
It was my understanding that `with-init!` was fired after page is finished constructing. However this will fire before all images and css have downloaded.

Timing difference:
http://stackoverflow.com/questions/588040/window-onload-vs-document-onload

Can we add the following to give better control of page load events, or change `with-init!`.

``` clojure
;; hoplon.core.cljs
(defn on-window-load [f] (.on (js/jQuery js/window) "load" f))

;; hoplon.core.clj
(defmacro with-window-load
  "Evaluates the body when the page has completed all loading (css and images)."
  [& body]
  `(defonce window-load# (on-window-load (fn [] ~@body))))
```

**Comment by thedavidmeister** [comment]
interesting, i tackled this with a cell like:

```
; True if "load" has triggered on the window.
(def loaded? (j/cell nil))
```

**Comment by flyboarder** [comment]
seems the current load event is on the window, closing for now.
