### ISSUE TITLE
jQuery does not support camelCase attributes used by SVG

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#173]
camelCase attribute names are pretty rare, but the SVG spec does call for it.

For example `startOffset` https://www.w3.org/TR/SVG/text.html#TextPathElementStartOffsetAttribute

Using the standard approach the attributes are lower-cased automatically, e.g. this fails:

```clojure
(textPath :xlink/href "#my-curve" :startOffset "25%" "foo")
; <textPath href="#my-curve" startoffset="25%">foo</textPath>
```

The only way I could get this to do what I wanted was with an awkward `with-let` wrapper like:

```clojure
(with-let [el (text-path :xlink/href "#my-curve" "foo")]
 (.setAttribute el "startOffset" "15%"))
; <textPath href="#my-curve" startOffset="25%">foo</textPath>
```

I think this SO post is relevant: https://stackoverflow.com/questions/26457455/setting-attribute-value-of-an-element-in-camelcase-using-a-directive

**Comment by thedavidmeister** [comment]
FYI, this also appears to break (lowercase) the `viewBox` attribute, which is pretty important for SVG.

**Comment by thedavidmeister** [comment]
looking a little more into this it appears that SVG support in general is out of scope for jQuery core:

- https://bugs.jquery.com/ticket/11166
- http://keith-wood.name/svg.html
- https://stackoverflow.com/questions/12361971/does-the-attr-in-jquery-force-lowercase

but `hoplon.core` already uses `.setAttribute` which is what SVG attributes like `viewBox` need. It is only in `hoplon.jquery` that `:svg/*` is overriden to use jQuery's `.attr` method.

Seems to me like if we removed the `:svg/*` override in the jQuery namespace then the default behaviour would be reinstated for SVG attributes and then `:svg/viewBox` would work.

**Comment by flyboarder** [comment]
That seems correct, could you test with hoplon.goog and see if this issue is resolved. It doesn't have those SVG override.

**Comment by thedavidmeister** [comment]
yeah, now that https://github.com/hoplon/hoplon/issues/174 has been merged in I'm going to try to migrate to `hoplon.goog` again, hopefully sometime this week.

**Comment by thedavidmeister** [comment]
@flyboarder i would estimate that I'm about 20% of the way through migrating away from jQuery and unfortunately I'm already running into multiple problems that should be resolved upstream:

https://github.com/hoplon/hoplon/issues/188
https://github.com/hoplon/hoplon/issues/186

This `with-let` style adding of `svg` attributes manually one at a time is starting to get pretty messy in my project so I'm proposing that we write a simple `hoplon.jquery/set-svg-attributes!` function as an immediate solution for this problem.
