### ISSUE TITLE
hoplon.goog do! sets attributes to `"null"` instead of removing them when val is `nil`

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#174]
Just noticed this when running my test suite requiring `hoplon.goog` instead of `hoplon.jquery`.

Expected:

```clojure
(div :data-foo (cell= (when foo "foo")))
(reset! foo true)
; <div data-foo="foo"></div>
(reset! foo false)
; <div></div>
```

Actual:

```clojure
(div :data-foo (cell= (when foo "foo")))
(reset! foo true)
; <div data-foo="foo"></div>
(reset! foo false)
; <div data-foo="null"></div>
```

This at least breaks `[data-foo]` style CSS selectors that only look for the existence of the attribute.

**Comment by flyboarder** [comment]
@thedavidmeister thanks for reporting this, i'll get a patch in.

**Comment by flyboarder** [comment]
looking at the code for this one, appears that both are plagued with the same problem, values are always passing the `(= false v)` check, the difference is that jquery is correctly handling the `nil` case.

The fix is to change `(if (= false v) ...` -> `(if-not v ...` patch to follow.
