### ISSUE TITLE
something like on! for upcoming *Observer browser APIs

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#176]
So far I'm aware of:

- `MutationObserver` = respond to DOM attributes/elements changing
- `PerformanceObsever` = more of a debugging/profiling tool
- `IntersectionObserver` = respond to a DOM element becoming visible in the viewport
- `ResizeObserver` = respond to a DOM element's box model changing dimensions

The first one seems pretty un-hoplon as it goes against 1-way data flow idea, although i'm sure there are some edge cases i haven't thought of.

The last two though, are pretty useful as they're more like user interaction events. I assume there will be more proposals for similar observers in the coming years as they really expose some information that was difficult or impossible to get at reliably, but pretty common for devs to want it.

Unfortunately, it's still at the point where you have to use a polyfill to achieve other of the latter 2, but I thought I'd open up an issue/discussion anyway to see if there's interest.

https://developers.google.com/web/updates/2016/10/resizeobserver
https://developers.google.com/web/updates/2016/04/intersectionobserver

**Comment by thedavidmeister** [comment]
For anyone who might want to use something like this in their own code.

There is a resize observer polyfill in cljsjs now:

https://github.com/cljsjs/packages/tree/master/resize-observer-polyfill

Here is an example implementation of a resize observer on a DOM element (doesn't use `on!` but the functionality is similar).

https://github.com/thedavidmeister/wheel/blob/master/src/wheel/resize_observer/hoplon.cljs

**Comment by flyboarder** [comment]
After attempting to implement this, I am suggesting a core change #217

**Comment by flyboarder** [comment]
There is initial work on this in the hoplon/brew#36 PR.

**Comment by flyboarder** [comment]
The required changes for hoplon are in `7.2` branch
