### ISSUE TITLE
Bootstrap Navbar button doesn't work with `hoplon.svg`

### ISSUE THREAD

**Issue by mudphone** [hoplon/hoplon#178]
I'm not sure if this is a Hoplon bug, but when I require `hoplon.svg` in a project where the [Bootstrap Navbar](http://getbootstrap.com/components/#navbar-default) is used, the navbar button stops working. When pressed, the button removes the entire HTML body, leaving the screen blank. The button I'm talking about is the "hamburger" (three horizontal lines) button which only displays when the browser window is small (mobile layout). When clicked, the button should display a dropdown menu of items from the fully expanded navbar menu.

If I remove the require for `hoplon.svg` the navbar works properly (but then I can't use `hoplon.svg`). My current work-around is to copy the entire `hoplon.svg` namespace's code into a new namespace in my project. I'd be happy to try to help fix this, although I'm not quite sure how to start.

I've created a [minimal project repo](https://github.com/mudphone/HoplonNavbarSvgProblem) to show how it is broken.

Thanks. I love Hoplon!

**Comment by flyboarder** [comment]
@mudphone The issue seems to be somewhere else, when you convert the .hl file to .cljs and include hoplon normally your example throws errors in the base cljs file.

**Comment by mudphone** [comment]
I changed `src/index.cljs.hl` to `src/app/main.cljs` and adde a require for `hoplon.core`. I was able to get the same problem to show up when `hoplon.svg` is required.

I updated the [demo repo here](https://github.com/mudphone/HoplonNavbarSvgProblem/commit/ef3c90ee306e593a91a6f6071380247c5c6196f1).

**Comment by flyboarder** [comment]
@mudphone could you try with the 7.1-SNAPSHOT?

**Comment by mudphone** [comment]
@flyboarder I [bumped the deps](https://github.com/mudphone/HoplonNavbarSvgProblem/commit/3600f023a7eb830867721f69c37fd2051babee61) to 7.1-SNAPSHOT and related. Unfortunately, the same problem occurs, where the "hamburger menu" button causes the HTML body to disappear.

```clojure
-  :dependencies '[[adzerk/boot-cljs          "1.7.228-2"]                                                                                  
-                  [adzerk/boot-reload        "0.4.13"]                                                                                     
-                  [hoplon/hoplon             "6.0.0-alpha17"]                                                                              
-                  [org.clojure/clojure       "1.8.0"]                
-                  [org.clojure/clojurescript "1.9.293"]              
+  :dependencies '[[adzerk/boot-cljs          "2.1.2"]                
+                  [adzerk/boot-reload        "0.5.1"]                
+                  [hoplon/hoplon             "7.1.0-SNAPSHOT"]       
+                  [org.clojure/clojure       "1.9.0-beta2"]          
+                  [org.clojure/clojurescript "1.9.946"]
```

**Comment by flyboarder** [comment]
This could be related to the internal prototype overrides which we are attempting to refactor.

**Comment by flyboarder** [comment]
@mudphone could you try with `7.2-SNAPSHOT` this version removed the prototype overrides which were probably to blame for this.

**Comment by thedavidmeister** [comment]
I tried to reproduce this in chrome after forking the example repo:

<img width="541" alt="screen shot 2018-01-02 at 6 37 05 pm" src="https://user-images.githubusercontent.com/629710/34477192-0902ffac-efec-11e7-93c9-7399087104d2.png">

worked OK for me in chrome using `7.1.0` (not snapshot). @mudphone could you test with the release version of `7.1.0`?

I did discover https://github.com/hoplon/hoplon/issues/221 though, which is annoying

**Comment by mudphone** [comment]
It works for me with 7.1.0 and 7.2.0-SNAPSHOT. Thanks!
