### ISSUE TITLE
migrate from selenium based testing to cljs tests (i.e. using doo)

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#191]
pros:

- all the web driver wrappers i know about for clojure are essentially unmaintained
- selenium seems to inevitably come with "random" bugs (a lot of race conditions) that cause builds to fail quite often when you have 1k+ assertions
- cljs tests are at least one or two OOM faster because there's no need to setup a web server and render entire pages to test one tiny element in the DOM
- it's much easier to write tests that make assertions directly against fresh DOM elements generated by hoplon than trying to scrape a large prefabricated global DOM shared by many tests (e.g. what if a previous test mutated the element that you want to inspect?)
- selenium commonly breaks when a new version of chrome/firefox comes out, not because your code is broken but because web driver needs an update to its interface with the browser version you want to use
- writing cljs tests comes with significantly less boilerplate and fixtures to maintain so the barrier to entry is lower and they can be written much faster
- cljs tests can be run in many different browsers, just like selenium
- if there were many tests it would be easier, and the benefits more obvious, of running cljs tests in parallel
- cljs tests are written in cljs not clj so they can optionally live with the code being tested, selenium tests are clj based so the codebase structure becomes a bit more clunky
- because we're dealing with tests in cljs not clj it would be easier to do things like running a test suite once for `hoplon.jquery` and again for `hoplon.goog` as we can just control what namespaces are pulled in directly. A selenium based approach would require maintaining two near-identical pages to be served/tested against, one with jquery and one with goog.

cons:
- selenium does have handy functions for triggering browser events that may need to be re-implemented to some extent for convenience (although jQuery helps a _lot_ here with `trigger()`)
- some browser behaviour is inconsistent between detached elements and those that are appended to the document. These problems are usually not too hard to spot (because the detached behaviour is just nonsensical, like events completely failing to bubble) and elements can still be attached/detached to the document manually in cljs tests.
- selenium style testing is better at end-to-end testing than cljs, but this type of testing seems inappropriate for the Hoplon framework itself, you might want to use it in a specific app though
- selenium is a much more natural fit for testing things like navigation/routing as it expects tests to span multiple page loads

**Comment by thedavidmeister** [comment]
Also, worth noting that moving the existing tests to cljs doesn't make it impossible to re-implement selenium tests in the future.

This is just pointing out that the _current_ tests and the tests we are _likely to write in the immediate future_ are all better handled by doo.

**Comment by thedavidmeister** [comment]
@flyboarder OK, PR up at https://github.com/hoplon/hoplon/pull/198

**Comment by flyboarder** [comment]
Merged!
