### ISSUE TITLE
normalising-classes causes repeated class to appear only once

### ISSUE THREAD

**Issue by freakinruben** [hoplon/hoplon#195]
I'm trying to use hoplon with semantic-ui, and I was wondering how I can make a css-class repeat in one element. Hoplon uses repeated classes for making a [grid responsive](https://semantic-ui.com/examples/grid.html):
```html
<div class="eight wide mobile six wide tablet four wide computer column" />
```
But if I try something like that with hoplon, only 1 `wide` class is left, which removes the responsiveness of semantic-ui:
```cljs
(h/div :class [:eight :wide :mobile
               :six :wide :tablet
               :four :wide :computer
               :column])
```
Results in:
```html
<div class="eight wide mobile six tablet four computer column" />
```

It looks this is because [`normalize-class`](https://github.com/hoplon/hoplon/blob/master/src/hoplon/core.cljs#L62) changes the vector into a map. So my question is, how can I accomplish multiple repeated (`wide`) class-names on the same element?

**Comment by flyboarder** [comment]
Currently you can't, this is a limitation of normalize-class like you mentioned.

What you can do is create your own implementation of `:class`.

**Comment by freakinruben** [comment]
If anyone else runs into this issue, you can set the classes directly on the element with GCS and your own attribute provider:
```cljs
(defmethod do! :class
  [elem _ classes]
  (let [classes (if (string? classes)
                  (h/normalize-class classes)
                  classes)]
    (if (vector? classes)
      (domcl/set elem (->> classes (map name) (clojure.string/join " ")))
      (doseq [[c p?] classes]
        (domcl/enable elem (name c) (boolean p?))))))
```
