### ISSUE TITLE
calling hoplon.core/body from phantomjs throws an error

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#197]
I see this if i call `hoplon.core/body` from any test:

`#object[TypeError TypeError: null is not an object (evaluating 'this$.hoplonKids = null')]`

**Comment by flyboarder** [comment]
@thedavidmeister boot-cljs-test now supports chrome headless, we should switch to that for hoplon since phantomjs no longer has any maintainer.

**Comment by thedavidmeister** [comment]
@flyboarder i think this is caused by `js/document` not having a body (it is assumed by hoplon to exist).

can be fixed pretty easy by creating if not exists.

**Comment by thedavidmeister** [comment]
this is a dupe of #175
