### ISSUE TITLE
when-tpl can still throw the warning about 0 arity atom call

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#200]
Still seeing this in a `when-tpl` even after upgrading to `7.1.0-SNAPSHOT`:

`WARNING: Wrong number of args (0) passed to cljs.core/atom`

**Comment by flyboarder** [comment]
Should be fixed!

**Comment by opyate** [comment]
> Should be fixed!

In which version?

**Comment by flyboarder** [comment]
7.1.0-SNAPSHOT

Matthew Ratzke
Founder | Degree9 Solutions Inc.
Degree9.io
________________________________
