### ISSUE TITLE
write tests for internal accounting of `hoplonKids` in response to various managed/unmanaged behaviour

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#209]
current tests in #205 are quite basic and aren't really targeting the internal state of elements, added this issue as a followup

**Comment by flyboarder** [comment]
This should be unneeded, the hoplonKids property only exists for managed elements.

**Comment by thedavidmeister** [comment]
@flyboarder potentially your most recent refactor makes this abstraction less leaky so it wouldn't need direct tests

**Comment by thedavidmeister** [comment]
i'm happy to close for now
