### ISSUE TITLE
refactor to avoid overriding js/Element prototype

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#210]
surely there's a better way to achieve what is being done here without modifying the prototype directly?

**Comment by flyboarder** [comment]
Refactor in progress, this makes 2 significant changes:
1. No More prototype overrides, we cannot do Hoplon things to native elements (append cells), the `.*child` methods are left untouched.
2. Elements are "upgraded" to hoplon elements when they either:
 - Are created inside `hoplon.core` (ex. `h/div`)
 - Are passed through the public API (ex. `(append-child! parent child)`)

**Comment by flyboarder** [comment]
refactor complete, what changed?
- no more managed property (we check the protocol IHoplonElement now)
- inline all the managed code to the protocol
- explicitly extend hoplon elements with IHoplonElement
- explicitly extend native elements via the public API
- only implicit modifications are ILookup and IFn
- Implementing IFn is a Hoplon feature and it's usage on native elements will upgrade them.
