### ISSUE TITLE
pull experimental code out of hoplon.core

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#211]
everything commented as "experimental" or only used by something experimental can be shipped out to a different namespace and/or repo.

hoplon.core should only contain well battle tested and commonly used functionality.

**Comment by flyboarder** [comment]
In the `7.2` branch everything has been moved to `hoplon.experimental`, I'll move that file to `hoplon/brew` prior to release.

**Comment by flyboarder** [comment]
`experimental` ns moved to hoplon/brew and released as `7.2.0-SNAPSHOT`.
Tracking hoplon version for future brew releases, to keep features in sync.
