### ISSUE TITLE
parinfer support

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#213]
a lot of hoplon files trigger parinfer warnings:

<img width="442" alt="screen shot 2017-12-24 at 7 13 09 pm" src="https://user-images.githubusercontent.com/629710/34325160-7f7ed120-e8de-11e7-8e1e-e7da83920d8b.png">

parinfer is a really cool IDE addition for clojure editing - https://shaunlebron.github.io/parinfer/

all that would need to change for hoplon to support parinfer would be some minor tweaks to whitespace through the project.

**Comment by flyboarder** [comment]
I have been doing this while working on `7.2` opening all the files should be enough to fix it.

**Comment by flyboarder** [comment]
All the files have been opened with parinfer enabled.

**Comment by thedavidmeister** [comment]
woo!
