### ISSUE TITLE
the defensive handling of body breaks embedded hoplon when the script is included in the head

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#221]
because the body doesn't exist when the script is executed from the head it will make an empty body, then the "real" body that hoplon is being injected into is a second body, which at least chrome completely ignores

**Comment by thedavidmeister** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/head

> document.head is read-only. Trying to assign a value to this property will fail silently or, when in ECMAScript Strict Mode in a Gecko browser, throw a TypeError.

https://developer.mozilla.org/en-US/docs/Web/API/Document/body

> Though body is settable, setting a new body on a document will effectively remove all the current children of the existing <body> element.

**Comment by thedavidmeister** [comment]
i put up a PR that shifts the defensive logic to when `body` is called, rather than when it is defined.

**Comment by flyboarder** [comment]
Fixed in latest `7.2-SNAPSHOT`.
