### ISSUE TITLE
missing tagsoup dep

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#232]
`java.io.FileNotFoundException: Could not locate pl/danieljanus/tagsoup__init.class or pl/danieljanus/tagsoup.clj on classpath.`

need to add `[clj-tagsoup/clj-tagsoup "0.3.0"]` as a dep

**Comment by flyboarder** [comment]
currently we use tagsoup within the boot pod dependencies, what task are you calling that errors?

**Comment by thedavidmeister** [comment]
`boot watch build-jar` in hoplon then the error popped up when using it as a checkout in the other repo

**Comment by mynomoto** [comment]
We do not recommend using boot anymore, and also do not use it on the Hoplon project itself, so I'm closing this.
