### ISSUE TITLE
`when-dom` still present in `on!` in hoplon.jquery and hoplon.goog

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#235]

**Comment by jjttjj** [comment]
Related to this: the `hoplon.goog` namespace calls `when-dom` right now without referring it here:
https://github.com/hoplon/hoplon/blob/master/src/hoplon/goog.cljs#L120

This issues a warning when requiring `hoplon.goog` and presumably breaks when it is actually used.

**Comment by flyboarder** [comment]
PR for this issue is up #243

**Comment by mynomoto** [comment]
This was fixed by #243
