### ISSUE TITLE
Is that possible combine a virtual DOM lib into hoplon base?

### ISSUE THREAD

**Issue by wind13** [hoplon/hoplon#240]
I guess many developer will compare hoplon with reagent etc. I like hoplon syntax, it looks simple and straightforward. I don't know the performance different between hoplon and reagent. But I think virtual DOM can bring a lot of benefit into framework. So is that possible combine a virtual DOM lib (like vdom etc.) into hoplon base?

**Comment by flyboarder** [comment]
I would argue that with hoplon this would have negative performance impacts. One of the benefits to hoplon is the lack of virtual Dom.

**Comment by thedavidmeister** [comment]
@wind13 could you explain where/how you expect the virtual DOM to improve performance?

Hoplon has no concept of HTML, only DOM, so there's no diff to be done of HTML data structures that usually necessitates a virtual DOM...

Diffing and caching of unchanged dynamic data is done internally to javelin cells, well before Hoplon gets involved.

**Comment by wind13** [comment]
Okay, cool, maybe I need to think this deeper.  So that means Javelin already done the virtual DOM things? no need virtual DOM then.

**Comment by thedavidmeister** [comment]
@wind13 sort of? javelin cells do have an internal cache that achieves something like a diff

There's simply no "render" step in hoplon though, you're _always_ working with native JS elements - https://codeburst.io/what-is-hoplon-13d11cd7bbc2

Without a render step, i don't know how a virtual DOM fits in the picture, it might but you'd have to outline how that would work and what the benefits/tradeoffs are...

on the other hand, there might be alternate algorithms/heuristics for calculating DOM manipulations we could think of that are more efficient ways to mutate the DOM based on _data_ diffs in javelin cells - but it would be worth treating each of these as it's own proposal with use case, research and code

**Comment by wind13** [comment]
That document help me to rethink about HTML and DOM with JavaScript data.

Hoplon is an abstraction and extension of the native JavaScript DOM API.

Thanks, I learned a lot.
