### ISSUE TITLE
Hoplon on ClojureScript Podcast

### ISSUE THREAD

**Issue by jacekschae** [hoplon/hoplon#270]
Hi!

I'm the host of ClojureScript Podcast and had @flyboarder already on the show talking about Boot. I reached out to @flyboarder about that but haven't heard back. Maybe my mails end up in spam? I'm trying via this channel to see if there would be anyone interested about talking Hoplon on ClojureScript Podcast.

@micha or @alandipert would you be interested? I would love to talk to you about Hoplon. It's not only my interest people are asking for Hoplon on CLJS Podcast; via SoundCloud

> Hi Jacek,
> 
> Just to say I'm really enjoying the podcasts and thanks for doing them.
> I wanted to ask you if you've considered trying to track down one of the Hoplon creators/maintainers? What seems interesting about that framework is that it's both full-stack, like Fulcro, and it's very different from all the rest in that it doesn't use react, and is more lispy. I thought I might build an app with it even if I don't actually use it for production, because it seems would learn a lot (like people say about lisp - but we now use lisp in production too of course). Would be amazing to get an update on the current state of Hoplon... I think that in general the informal, tacit knowledge conveyed in a podcast is invaluable - it makes taking on documentation, for example, so much easier; when it feels like you've just had a chat with the creator, introducing background, history, motivations.
> 
> Best wishes & thanks for doing these!
> 
> Mike Walker

**Comment by flyboarder** [comment]
Hi Jacek, I'm just really busy right now - would love to chat about Hoplon on the Podcast!

**Comment by jacekschae** [comment]
When could we do this? When would you be available? Would be great to understand your timelines.

**Comment by alandipert** [comment]
Hi I'm not actively involved in hoplon at the moment but I'd be happy to join the podcast and provide historical context. Thanks for the invitation!

**Comment by jacekschae** [comment]
Closing this one. Recorded an episode with Alan!
