### ISSUE TITLE
NSFW link in the wiki HLisp page

### ISSUE THREAD

**Issue by ohmree** [hoplon/hoplon#271]
[The page in question.](https://github.com/hoplon/hoplon/wiki/HLisp)

The lispyscript domain seems to now have nsfw content on it so the link to it should probably be removed.

**Comment by daveyarwood** [comment]
Yikes! Thanks for reporting this. Judging by [this issue](https://github.com/santoshrajan/lispyscript/issues/71), I think that's the same project, so I'll update the link in the wiki to point to that GitHub repo instead.

**Comment by daveyarwood** [comment]
Wiki updated. I think we can close this issue now.

**Comment by ohmree** [comment]
Good, closing.
