### ISSUE TITLE
docs on boot2 and migration

### ISSUE THREAD

**Issue by ul** [hoplon/hoplon#60]
starting point about differences is here http://hoplon.discoursehosting.net/t/porting-hoplon-to-boot2/405
working ported app: https://github.com/tailrecursion/hoplon.io/tree/boot2

**Comment by mynomoto** [comment]
Hi @ul sorry for taking this long to answer.

And because so much time has passed I think this is not an issue anymore. Sorry. :disappointed: 

I'm closing this but if you think this is still a concern please reopen it.
