### ISSUE TITLE
fix vendors and contrib

### ISSUE THREAD

**Issue by ul** [hoplon/hoplon#61]
vendors: migrate to `cljsjs` where possible, provide as `:foreign-libs` where impossible
contrib: do not forget to enable `:lib` flag

**Comment by bsima** [comment]
Instead of a custom vendors directory, would it be prudent to use [cljsjs/packages](https://github.com/cljsjs/packages)? Or a similar format, something like tailrecursion/hoplon-addons?

**Comment by ul** [comment]
yes, my vote is on `cljsjs` for vendors, and some new repo for contribs

**Comment by flyboarder** [comment]
Closing as both vendors and contrib have been resolved. 

Contrib repo is here #boot/brew
