### ISSUE TITLE
How to include Hoplon for using with linters and other stuff that requires “java -jar ...” to execute 

### ISSUE THREAD

**Issue by weaver-viii** [hoplon/hoplon#63]
<i>First of all, this is not a question about atom.io editor or anything else.</i>

Of course linters doesn't know about external dependencies
and I'm trying to NOT treating hoplon stuff like errors. It requires 'clojureExecutablePath' which later becomes 

<pre> "java -jar" + "clojure.jar" + " -i" (although this command can be rewritten ). </pre> 

How to include hoplon stuff like (<b>page</b> "index.html") in namespace for treating them as safe and not like errors?

I discovered some code to start in defined namespace, but I'm not sure about that.

<pre> java -cp .;clojure-1.6.0.jar; clojure.main -e \
"(ns hoplon) (clojure.main/repl) (in-ns 'hoplon) (clojure.core/use 'tailrecursion/hoplon)"  </pre> 

this is code for linter:
https://github.com/AtomLinter/linter-clojure/blob/master/lib/linter-clojure.coffee#L30

**Comment by micha** [comment]
I'm not sure I fully understand what you're trying to do. The `*.hl` files aren't really Clojure or ClojureScript files---they need to be compiled into ClojureScript by the Hoplon compiler (this is why they have the special extension). I think maybe what you want to do is configure tools to ignore `*.hl` files. Otherwise you'd need to have a linter that understands Hoplon pages.

**Comment by weaver-viii** [comment]
Hi micha,
Yeah, that's the point. :dancers: Thank you very much for your answer. :ghost: 
In the future I'll try to modify a linter to understand Hoplon pages. :smiling_imp: :smiley_cat:

**Comment by flyboarder** [comment]
@weaver-viii add this to your config for to make .hl files use clojure grammar:
```
"*":
  core:
    customFileTypes:
      "source.clojure": [
        "hl"
      ]
```

**Comment by mynomoto** [comment]
I think this is solved, please someone reopen it if you don't agree.
