### ISSUE TITLE
FOUC - Flash Of Unstyled Content

### ISSUE THREAD

**Issue by LauraSempere** [hoplon/hoplon#66]
For a short while the unstyled content appears in the browser even on Hoplon 6.0.0-alpha2, but the issue was always present, even in Hoplon 5.x.x.

Showcasing the issue on [our homepage](http://www.stg.exicon.mobi/appboard/pricing/):
[FOUC - Flash Of Unstyled Content](https://clojurians.slack.com/files/onetom/F097SG9J4/fouc_-_http-__www.stg.exicon.mobi_appboard_pricing_.mov) (play it frame by frame)

**Comment by flyboarder** [comment]
@LauraSempere have you tried using prerender? This resolved all of my FOUC issues.

**Comment by mynomoto** [comment]
I'm closing this, @LauraSempere please reopen if the proposed solution didn't work.
