### ISSUE TITLE
Basid demo doesn't work.

### ISSUE THREAD

**Issue by MrSpock** [hoplon/hoplon#67]
Hi,
Something is broken somwhere. I can't run basic demo:

`mbspock:~/chmura/nauka$ lein new hoplon-castra lab
mbspock:~/chmura/nauka$ cd lab
mbspock:~/chmura/nauka/lab$ boot development
java.io.FileNotFoundException: Could not locate tailrecursion/hoplon/boot__init.class or tailrecursion/hoplon/boot.clj on classpath: , compiling:(/Users/spock/chmura/nauka/lab/.boot/tmp/83793/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:23:44)
↳ Caused by: Could not locate tailrecursion/hoplon/boot__init.class or tailrecursion/hoplon/boot.clj on classpath:
mbspock:~/chmura/nauka/lab$
`

**Comment by onetom** [comment]
@MrSpock the hoplon-castra template requires [boot1](https://github.com/tailrecursion/boot) if I remember well. I never tried it with [boot2](http://boot-clj.com/), but it's most likely the reason for your error.

The Hoplon project is in the middle of a transition from v5 to v6.
This transition has just started this weekend.
As part of it the http://hoplon.io/ site will be revamped and the [demos](https://github.com/hoplon/demos/tree/hoplon6) will be updated to work with Hoplon6 too.

If you sign up to the http://clojurians.net/ Slack team, we can give you real time assistance on the #hoplon channel to try the system out.

Don't be discourage this initial road block. Quite a few of us is using Hoplon in production, so serious issues are guaranteed to be fixed quite fast.

**Comment by MrSpock** [comment]
@oneatom:

That was boot1. Here is result of both boot's :)
`
bspock:~/chmura/nauka/lab$ boot development

java.io.FileNotFoundException: Could not locate tailrecursion/hoplon/boot__init.class or tailrecursion/hoplon/boot.clj on classpath: , compiling:(/Users/spock/chmura/nauka/lab/.boot/tmp/86255/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:23:44)
↳ Caused by: Could not locate tailrecursion/hoplon/boot__init.class or tailrecursion/hoplon/boot.clj on classpath:
mbspock:~/chmura/nauka/lab$ boot2 development
java.lang.RuntimeException: No reader function for tag tailrecursion.boot.core/version
                      ...
 clojure.core/read-string  core.clj: 3663
boot.util/read-string-all  util.clj:  207
          boot.main/-main  main.clj:  140
                      ...
         boot.App.runBoot  App.java:  242
            boot.App.main  App.java:  356
mbspock:~/chmura/nauka/lab$
`
I'm not giving up :-) - I'm starting to suspect that something is wrong with my boot ..

**Comment by MrSpock** [comment]
I can confirm that it's not something with my env.
I just downloaded boot(1) and lein on clean CentOS install and error is exaclty the same.

**Comment by onetom** [comment]
I'm trying it on my Mac too as we speak. In the meantime can you share the your java version, pls?

**Comment by MrSpock** [comment]
@onetom 

My Mac:
mbspock:~$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
mbspock:~$

Linux (CentOS):
[spock@CentOS-HFC test]$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b13)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
[spock@CentOS-HFC test]$


It was working on Friday :)

**Comment by onetom** [comment]
I see what's the problem. The template script tries to be smart and pulls the latest version of Hoplon which is not boot1 compatible anymore. If u change the dependency version in the `build.boot` file to this:
```
                  [tailrecursion/hoplon      "5.10.25"]]
```
then `boot development` works.
