### ISSUE TITLE
first-class support for prerendering multi-page sites?

### ISSUE THREAD

**Issue by jab** [hoplon/hoplon#70]
Some discussion around this in Slack got my hopes up, so wanted to capture that here and ask more directly about priority (excerpted+paraphrased):

> @jab: Hey @alandipert, great to see the new Get Started page! I've been wondering about the "Hoplon is for single-page web applications" thing. Is that unnecessarily limiting / isn't Hoplon still useful when you need multiple pages? FWIW the potential to use Hoplon for prerendering multi-page sites was a big draw for me, but I might have misunderstood how well it's supported.
> @onetom: @jab: we are generating our homepage with hoplon. what's not solved about it is how to minimize compilation time. currently for every hoplon `(page ...)` there is a full google closure lib, jquery etc emitted into the `target` dir. we are sharing our [layout](https://github.com/exicon/homepage/blob/master/src/homepage/layout.cljs.hl#L106-L162) amongst our pages, so when we are working on the layout itself, all pages are recompiled on every change which takes 20-30 seconds all together. so while technically it's possible to use hoplon as a static site generator, i wouldn't recommend it just yet until we have a better model to handle the multipage app case.
> as a workaround i turned the whole site into a SPA and pre-render it from under different paths.
this was not an easy sail either because the phantomjs pre-rendering js snippet was accessing the page thru the `file://` protocol, so when i was getting the path with `(.. js/window -location -pathname)` ([src](https://github.com/exicon/homepage/blob/master/src/homepage/index.cljs.hl#L295-L316)) i get `/Users/onetom/exicon/homepage/target/index.html` during prerendering and `/index.html` on production over `https://`...
> so to understand all these quirks and account for them in your code is what makes me think it's better NOT to recommend (boot-)hoplon as a static site builder

How much interest is there in having a good story for the multi-page app use case? Is there anything the community can do to help improve support?

Thanks!

**Comment by levitanong** [comment]
I can't say much about the road map, as I'm not part of the dev team, but there are two community boot tasks that might be able to scratch your itch for static site generation:

https://github.com/hashobject/perun
https://github.com/DanThiffault/boot-pages

Both are listed in the boot community tasks list here:
https://github.com/boot-clj/boot/wiki/Community-Tasks

**Comment by alandipert** [comment]
I think it's unlikely for support for this to be "first-class" in Hoplon itself, becaus Hoplon is so focused on SPA.  But as @levitanong points out, other projects specialize in this.  Maybe a Hoplon plugin for one of the two projects he lists could bridge the gap.
