### ISSUE TITLE
elements inside `loop-tpl` lose `:click` functionality if loop collection mutates

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#78]
# Situation A
```
(def population (range 20))
(defc selected-population nil)

(div
  (button :click  #(reset! selected-population 
    (if (nil? @selected-population) 
      population 
      nil)) 
    "Populate")
  (ul 
    (loop-tpl :bindings [p selected-population]
      (li :click #(js/alert "yo") p)))
```

1. in the above, clicking on "Populate"  causes an unordered list to show. In this state, every list item is clickable, and will cause an alert to show.
2. When "Populate" is clicked again, `selected-population` is reset back to nil, and the unordered list disappears. When "Populate" is clicked once more, the unordered list from (1) shows again.
3. The expectation is for every list item to be clickable, causing an alert to show. However, this is not the case. None of the `:click`s trigger.

# Situation B
```
(def population-a (range 20))
(def population-b (range 5))

(defc selected-population nil)

(div
  (button :click #(reset! selected-population population-a) "Populate A")
  (button :click #(reset! selected-population population-b) "Populate B")
    (ul 
      (loop-tpl :bindings [p selected-population]
        (li :click #(js/alert "yo") p))))
```

1. In the above example, clicking on "Populate A" will cause an unordered list to appear, as in Situation A. If you were to click on each item, you'll find that the alerts appear as expected.
2. Clicking on "Populate B" also results in expected behavior.
3. Clicking back on "Populate A", however, results in peculiar behavior. Now, items 0 ~ 4 are clickable, but anything below that is not.

It's as if in `loop-tpl`, whenever the collection changes, the `:click`s only get applied up to the last index of the previous state of the collection.

**Comment by thedavidmeister** [comment]
I'm seeing something like this with `:keyup` and `:keydown`.

I have a set of text inputs in the page created with `loop-tpl`. I have a cell that tracks the state of the values of the inputs and adds a blank text input at the end of the set. If the user types in the last blank input, a new blank input will be automatically created. If an input with a value in it has the value deleted, the input is removed from the page. This is all kept up to date on `:keyup` and `:keydown`.

This is all OK when adding new inputs, but when you delete them and try to re-add them, the `:keyup` and `:keydown` events stop working past the number you deleted.

For example, if you create 4 inputs with values in them (with 1 blank one), then delete the 4th then you can no longer add values to more than 5 inputs (the 5th input does not update the state cell when typed in it, and the events do not fire to create a new, blank input). The 4th input still has the events bound, however, so I can delete it, leaving me with 3 inputs with values in them. I *can* then re-create up to 5 inputs (with no blank inputs, and the 5th input "defused"). If I delete *all* the inputs, I can only create 2 inputs - the first one will work, and the created blank input will be "defused" now.

Sorry, it's a little hard to describe, but it seems more or less to be what @levitanong reported. Hopefully this extra info helps.

**Comment by thedavidmeister** [comment]
FYI - my problem appears to be fixed by going *back* to Hoplon alpha10 (was using alpha11)

**Comment by levitanong** [comment]
Thanks for the heads up, @thedavidmeister! I'll try downgrading to alpha 10 for the project relevant to this issue. The workaround I'm using is hella ugly. :stuck_out_tongue_winking_eye:
