### ISSUE TITLE
Hoplon template doesn't work with the latest Boot 

### ISSUE THREAD

**Issue by acierto** [hoplon/hoplon#81]
I followed your instruction and did:
1) brew install boot-clj
2) lein new hoplon address-book
3) boot dev

When I do boot -u:

#https://github.com/boot-clj/boot
#Fri Jan 01 11:13:05 CET 2016
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.5
#App version: 2.2.0

Result:
Please download latest Boot binary: https://github.com/boot-clj/boot#install

Looks like that hoplon or boot or whatever in this chain of dependencies is not backward compatible

**Comment by laforge49** [comment]
The boot installer rarely needs to change, but it is possible you need to update it if the source of your boot install is quite old. Did you follow the directions given and install the new boot binary? Once you have updated the wrapper, the boot -u command should work across many future versions.

**Comment by micha** [comment]
@acierto it looks like your homebrew is out of date. Update homebrew and reinstall boot, it should work.

**Comment by alandipert** [comment]
Closing, but @acierto please do re-open if you still have any issues.
