### ISSUE TITLE
getting started: generated address-book directory does not match tutorial

### ISSUE THREAD

**Issue by kennytilton** [hoplon/hoplon#82]
I have been working thru the https://github.com/hoplon/hoplon/wiki/Get-Started guide on a brand new Ubuntu VM running under vmware on windows 10 and all went well until:

   lein new hoplon address-book

That actually went fine, but the resulting directory does not match at all the contents advertised in the tutorial. I just see .gitignore, project.clj, README, and two sub-directories, src and test. And src just has a hoplon directory containing core.clj. The README looks like a stub.

I tried: lein new hoplon-template address-book as well, and the castra template. Same result. It looks as if I am not getting a web client template, actually.

I think the only mistake I made following the tutorial was installing boot before leiningen. 

Did I miss a step?

Thx, kenneth

**Comment by alandipert** [comment]
@kennytilton that is weird.  My only thought is that perhaps your `lein` is not current.  What is the output of `lein -v`?

If it's anything less than 2.5.3 you could try to `lein upgrade` and then `lein new hoplon address-book` again.

Failing that I bundled up a fresh template for you - https://dl.dropboxusercontent.com/u/12379861/address-book.tar.bz2

If that works for you and we see the lein thing happen again we may just drop that URL into the tutorial.

**Comment by kennytilton** [comment]
Thanks, Alain. I did miss something: the warning that the package manager
might have a 1.x version, which it did. Ubuntu, btw.

I am up and running.

Thx again, Kenneth

On Sat, Jan 30, 2016 at 8:02 AM, Alan Dipert <notifications@github.com>
wrote:

> @kennytilton <https://github.com/kennytilton> that is weird. My only
> thought is that perhaps your lein is not current. What is the output of lein
> -v?
>
> If it's anything less than 2.5.3 you could try to lein upgrade and then lein
> new hoplon address-book again.
>
> Failing that I bundled up a fresh template for you -
> https://dl.dropboxusercontent.com/u/12379861/address-book.tar.bz2
>
> If that works for you and we see the lein thing happen again we may just
> drop that URL into the tutorial.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hoplon/hoplon/issues/82#issuecomment-177171362>.
>



-- 
Kenneth Tilton
54 Isle of Venice Dr
Fort Lauderdale, FL 33301

ken@tiltontec.com
http://tiltontec.com
@tiltonsalgebra

646-269-1077

"In a class by itself." *-Macworld*

**Comment by alandipert** [comment]
Great! I'll close this but if you have other issues let us know.
