### ISSUE TITLE
jQuery dep

### ISSUE THREAD

**Issue by boxxxie** [hoplon/hoplon#83]
I'm really curious as to why jQuery is used when cljs packages Googles lib.

**Comment by micha** [comment]
Basically, jQuery's market domination makes it way more attractive than Google Closure (GCL). jQuery market share is around 70%, compared to 0.004% for GCL. There are a number of specific reasons, but they all come back to the sheer size of the jQuery community:

1. We've found jQuery to be a more robust DOM compatibility layer than GCL. This is a result of thousands of commits from hundreds of committers, fixing weird compatibility issues.
2. jQuery is familiar to users already, and StackOverflow has thousands of answered questions about any issue you may every have about it (many Hoplon users are new to web development)
3. There are way more useful plugins for jQuery than there are for GCL. If you're going to be using jQuery plugins then you're going to need jQuery anyway, and most users do.

Consider the following hoplon snippet:

```clojure
(button :click (fn [event] (.log js/console "i'm clicked!")))
```

Hoplon uses jQuery to bind the `"click"` event to the event handler. By default Hoplon will bind any attribute whose value is a function to the jQuery event with the same name as the attribute, so you want to do something when a key is pressed? Easy, just google "jquery event key pressed" and you will learn that jQuery calls that event `"keypress"`, so you can do:

```
(input :keypress (fn [event] (.log js/console "i'm being typed in!")))
```

It's way harder to get info about GCL, the docs are verbose and incomplete.

**Comment by micha** [comment]
Also, it's not as if using the GCL stuff is free: using it adds code to the application that otherwise would not be there. I haven't done a full comparison, but I would expect that trading jQuery for the GCL equivalent namespaces would not be a huge saving in size (jQuery is around 35K minified and gzipped).

**Comment by boxxxie** [comment]
thanks, it's a little hard to understand this framework, even if it is very small. the design docs mentioned Googles lib. 

what if I want to focus on load time, what are my options for using native methods instead of jQuery. would I be able to easily replace/abstract out jQuery?

**Comment by micha** [comment]
There is no mechanism for replacing jQuery in Hoplon. I'm sure you could do it, but page load time is not our primary concern.

Hoplon is better suited to projects where you're most interested in managing the complexity of the application over time and keeping it simple even as new features are added and the application is extended to do new things.

The kinds of applications we make are single page apps (with the focus on "app"): think gmail vs instagram. For gmail, page load times are pretty far down on the list of things to optimize for, I imagine.

**Comment by micha** [comment]
Also, just to be clear, page load times are not a problem...we just don't make sacrifices elsewhere to optimize in this area. So far we've run into no problems with load times, we just use advanced GCL optimization level and gzip etc. Page load times are fine for the kinds of business applications we make.

**Comment by boxxxie** [comment]
I've been doing SPAs for 6 or so  years. 
Gmail features are not allowed to add load time from what I've heard. 
i don't mind jQuery, but some people do.

**Comment by micha** [comment]
Right, this is what I was saying :) We've found that adding features to our Hoplon applications don't add load time, and so on, so we haven't tried to fix what isn't broken. In an application like gmail, deciding whether to use jQuery or not based on the time it takes to transmit the 32K js file would be utterly foolish, no? They haev way bigger fish to fry with that application.

**Comment by micha** [comment]
One issue with jQuery is that it leaks event handlers if you don't call `jQuery#remove()` on elements that have event handlers attached. For example:

```clojure
(cell= (map #(div :click doit %) items))
```

When the `items` cell changes the divs will be removed from the DOM via `parent.removeChild(x)` (Hoplon doesn't remove items from the DOM with the jQuery remove method because that would remove event handlers and that would break any code that reinserts elements back into the DOM). This leaks the event handler which prevents GC of the removed elements.

One approach is to move the default `do!` and `on!` implementations to a separate namespace, `boot.jquery` for example. The user would need to `:require` that namespace to pull jQuery in. We could have a `hoplon.goog` namespace with equivalent `do!` and `on!` implementations, etc.

**Comment by dm3** [comment]
On topic of getting rid of jQuery. Current state:

* Hoplon currently uses a small subset of jQuery functions for the core functionality
  + `attr`, `prop`, `removeAttr`, `on`, `trigger`
* Some of the `do!` and `on!` multimethods use an extended set of jQuery functions
  + `focusin`, `offset`, `slideTo`, etc

What do we need?

* pull in the smallest amount of code by default
* avoid the event handler leaks
* drop support of IE9- browsers (non-evergreen) *(?)*

Approaches:

1. Hoplon code remains as is. We create a `hoplon-jquery` adapter lib which defines the needed fns. This would allow substituting the adapter with actual `jQuery`, `Cash.js` or `Zepto.js`. Support for older browsers is still possible by using an older version of jQuery. We can try doing this through additional protocols on `Element`, although I'm not sure if it's just additional unneeded complexity.
2. Replace `jQuery` fns by the modern DOM API usage/Google Closure. Browser compat bugs will have to be fixed directly in Hoplon.

What do you think?

**Comment by onetom** [comment]
Since Google Closure lib is pulled in anyway, I would think that's the most efficient way to implement it.
According to @micha GCL had issues. Is it still the case?
Aren't google's apps themselves using GCL?
Are they not cross-browser compatible?

**Comment by micha** [comment]
@onetom Is it true that GCL is pulled in anyway? It should not pull in any features of GCL that you don't use.

**Comment by onetom** [comment]
Sorry, I remembered seeing a lot of deps included by default, but indeed only a few are there:
```
onetom@retinatom /t/goog-test> boot -d seancorfield/boot-new new -t hoplon -n goog-test
onetom@retinatom /t/goog-test> cd goog-test
onetom@retinatom /t/goog-test> sed -i '' -e 's/ :opt.*/)/' build.boot

onetom@retinatom /t/goog-test> time boot prod target
Compiling Hoplon pages...
• index.cljs.hl
Compiling ClojureScript...
• index.html.js
Prerendering HTML files...
• index.html
Writing target dir(s)...
       20.64 real        22.17 user         2.03 sys

onetom@retinatom /t/goog-test> find target/ | ag goog
target//index.html.out/goog
target//index.html.out/goog/array
target//index.html.out/goog/array/array.js
target//index.html.out/goog/asserts
target//index.html.out/goog/asserts/asserts.js
target//index.html.out/goog/base.js
target//index.html.out/goog/debug
target//index.html.out/goog/debug/error.js
target//index.html.out/goog/deps.js
target//index.html.out/goog/dom
target//index.html.out/goog/dom/nodetype.js
target//index.html.out/goog/functions
target//index.html.out/goog/functions/functions.js
target//index.html.out/goog/iter
target//index.html.out/goog/iter/iter.js
target//index.html.out/goog/math
target//index.html.out/goog/math/math.js
target//index.html.out/goog/object
target//index.html.out/goog/object/object.js
target//index.html.out/goog/string
target//index.html.out/goog/string/string.js
target//index.html.out/goog/string/stringbuffer.js
target//index.html.out/goog/structs
target//index.html.out/goog/structs/map.js
target//index.html.out/goog/structs/structs.js
target//index.html.out/goog/uri
target//index.html.out/goog/uri/uri.js
target//index.html.out/goog/uri/utils.js
```

Which are modules required by ClojureScript itself:
```
onetom@retinatom /t/goog-test> cat target//index.html.out/cljs_deps.js
goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../tailrecursion/priority_map.js", ['tailrecursion.priority_map'], ['cljs.core', 'cljs.reader']);
goog.addDependency("../javelin/core.js", ['javelin.core'], ['cljs.core', 'tailrecursion.priority_map']);
goog.addDependency("../jquery.inc.js", ['cljsjs.jquery'], []);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../hoplon/core.js", ['hoplon.core'], ['cljsjs.jquery', 'javelin.core', 'goog.Uri', 'cljs.core', 'clojure.set', 'clojure.string', 'cljs.reader']);
goog.addDependency("../hoplon/app_pages/_index_DOT_html.js", ['hoplon.app_pages._index_DOT_html'], ['javelin.core', 'cljs.core', 'hoplon.core']);
goog.addDependency("../boot/cljs/main834.js", ['boot.cljs.main834'], ['hoplon.app_pages._index_DOT_html', 'cljs.core']);
```

**Comment by flyboarder** [comment]
This should be resolved now, jquery has been split from core in master and goog provider is available from hoplon/brew repo.

**Comment by flyboarder** [comment]
Jquery split is now complete.
