### ISSUE TITLE
webdriver testing

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#85]
so, I noticed that there's not a lot of testing going on here >.<

I've used https://github.com/semperos/clj-webdriver before, and got it working with hoplon + travis CI.

I've seen some issues that arguably would have been picked up by some tests, like https://github.com/hoplon/hoplon/issues/78

I say "arguably" because I detected the existence and also successful workaround with the hoplon version number rollback with one of the tests I was using at the time - so in theory it could have been caught by hoplon too :)

I'm not suggesting a particular process for writing/requiring tests atm, but having the *ability* to run them through boot is certainly useful.

**Comment by alandipert** [comment]
@thedavidmeister I agree there would be value, thanks for bringing it up!

I imagine the first step is creating some kind of harness and then introducing a simple test.  Travis sounds like a good choice - almost all of the Adzerk Boot projects are on Travis and it's worked really well for us.

Work toward this end would be much welcome.

**Comment by thedavidmeister** [comment]
@alandipert OK, I muddled something together at #87 and you can see passing builds at https://travis-ci.org/thedavidmeister/hoplon/builds but you or whoever owns the hoplon repo in github will have to setup Travis to see builds appear here against commits in github.

**Comment by thedavidmeister** [comment]
also, you can run `boot webdriver-tests` locally to see what it is actually doing, FYI
