### ISSUE TITLE
Document `defelem`

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#92]
This post from @micha really helped me understand `defelem` and why it is needed (why not just `defn`?) - http://hoplon.discoursehosting.net/t/defelem-is-it-used-internally-by-hoplon/106

Unfortunately there's nothing that clear on the wiki. It took me a few months to find the above article.

**Comment by thedavidmeister** [comment]
@levitanong and I made some progress at https://github.com/hoplon/hoplon/wiki/API-Documentation

**Comment by thedavidmeister** [comment]
Updated again tonight to explain `on!` and `do!` better

**Comment by levitanong** [comment]
Oh my god, @thedavidmeister, you’ve been incredibly thorough with the documentation. This is amazing, especially with the `do!` special cases.

**Comment by thedavidmeister** [comment]
@levitanong no problem, I learned a bunch in the process :)
