### ISSUE TITLE
document storage cells in the wiki

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#99]

**Comment by thedavidmeister** [comment]
micha [1:55 AM] 
@thedavidmeister: one thing about the storage atom that was recently(ish) added is the `:ignore-existing` keyword arg

[1:55] 
normally the storage atom will initialize itself with the value stored in local storage

[1:55] 
but sometimes you want to ignore what's in local storage and start with whatever is in the cell you're wrapping instead

[1:56] 
that's what that's for

**Comment by thedavidmeister** [comment]
thedavidmeister [1:57 AM] 
@micha: what about an explanation on how to implement your own storage backend?

micha [1:58 AM] 
sure

[1:59] 
a storage backend is basically a js object that has `.getItem(key)` and `.setItem(key, value)` methods

[2:00] 
so like suppose i define `js/firebaseStorage` for example

[2:01] 
 ```(function() {
  var firebaseStorage = {
    getItem: function(key) {...},
    setItem: function(key, value) {...}
  };
  window.firebaseStorage = firebaseStorage;
})()
```

[2:01] 
then i could do:

[2:02] 
 ```(defn firebase-storage
  [atom k & {:keys [ignore-existing]}]
  (html-storage atom js/firebaseStorage k :ignore-existing ignore-existing))
```


thedavidmeister [2:04 AM] 
@micha: ah ok, so that bit is usually done in raw JS and then just wrapped up for hoplon?

micha [2:05 AM] 
usually it comes from some other library

[2:05] 
like the localstorage and session storage are built into the browser

[2:05] 
you can use deftype to make a js type from cljs though

thedavidmeister [2:06 AM] 
do you know an example of that I can review?

micha [2:08 AM] 
hm so there is also another way

[2:08] 
you could implement IStorageBackend protocol on anything

[2:09] 
like this:

[2:12] 
 ```(defrecord FirebaseStorage [key]
  hoplon.storage-atom.IStorageBackend
  (-get [this not-found] ...)
  (-commit! [this value] ...))

(defn firebase-storage
  [atom k & {:keys [ignore-existing]}]
  (hoplon.storage-atom/store atom (FirebaseStorage. k) :ignore-existing ignore-existing))
```

thedavidmeister [2:14 AM] 
ok cool

[2:14] 
thanks :simple_smile:

**Comment by flyboarder** [comment]
Documentation provided at: https://github.com/hoplon/hoplon/wiki/Storage-Cells

**Comment by thedavidmeister** [comment]
@flyboarder i think you skipped a few steps in your docs :P

the docs should probably begin with a simple `local-storage` example to provide context if you've never seen or used a storage cell before.

**Comment by flyboarder** [comment]
Updated the documentation to start with an example, move through the public API and end with the underlying record and protocol.

I think this will suffice for closing this issue, if you want to extend the docs feel free.
